package snrdev_test

import (
	"time"

	"github.com/karn-zuvarna/snr-exam/app/snrdev"
)

type MockContactModel struct {
	ID int
}

var (
	now             = time.Date(2025, 9, 30, 8, 31, 0, 0, time.UTC)
	uuid            = "00000000-0000-0000-0000-000000000000"
	precitizenToken = snrdev.PreCitizenToken{
		Email:    "john.doe@example.com",
		Mobile:   "0888888888",
		MemberID: 1,
		UserID:   1,
	}
	preCitizenshipAppmanGetAllReturn = []snrdev.AppmanDB{
		{
			ID:             "appman-id-1",
			MemberID:       "1",
			VerificationID: "verification-1",
			UserID:         "1",
			IsFrontIDCard:  true,
			IsBackIDCard:   true,
			IsLiveness:     true,
			IsRecognition:  true,
			Status:         "completed",
			VerifiedStatus: true,
			DopaStatus:     true,
			FaceSimilarity: 0.95,
			Type:           1,
		},
		{
			ID:             "appman-id-2",
			MemberID:       "1",
			VerificationID: "verification-2",
			UserID:         "1",
			IsFrontIDCard:  true,
			IsBackIDCard:   true,
			IsLiveness:     true,
			IsRecognition:  true,
			Status:         "completed",
			VerifiedStatus: true,
			DopaStatus:     true,
			FaceSimilarity: 0.95,
			Type:           1,
		},
	}
	preCitizenshipPreMemberGetAllReturn = []snrdev.PreMemberDB{
		{
			ID:       "premember-001",
			Email:    "john.doe@example.com",
			Mobile:   "0888888888",
			MemberID: "1",

			Customer: snrdev.CustomerDetailsDB{
				ID:                   "1",
				CreatedBy:            "system",
				MemberID:             "1",
				Citizenship:          1,
				Title:                "นาย",
				ThName:               "จอห์น",
				ThMiddleName:         "",
				ThSurname:            "โด",
				EnName:               "John",
				EnMiddleName:         "",
				EnSurname:            "Doe",
				Mobile:               "0888888888",
				Email:                "john.doe@example.com",
				Agreement:            true,
				DateOfBirth:          now,
				Status:               1,
				IDCard:               "1234567890123",
				LaserCode:            "ABC123456789",
				ExpireDate:           now,
				SourceOfFunds:        1,
				KnowledgeTest:        true,
				KnowledgeTestVersion: "v1.0",
				Step:                 5,
				Type:                 1,
				Identify:             1,
			},

			Appman: snrdev.AppmanDB{
				ID:             "appman-id-1",
				MemberID:       "1",
				VerificationID: "verification-1",
				UserID:         "1",
				IsFrontIDCard:  true,
				IsBackIDCard:   true,
				IsLiveness:     true,
				IsRecognition:  true,
				Status:         "completed",
				VerifiedStatus: true,
				VerifiedAt:     &now,
				ExpiresAt:      &now,
				DopaMessage:    "Verification successful",
				DopaStatus:     true,
				FaceSimilarity: 0.95,
				Type:           1,
			},

			SuiteTest: snrdev.SuiteTestDB{
				ID:          "suitetest-001",
				CreatedBy:   "system",
				MemberID:    "member-001",
				TotalScore:  85,
				Acknowledge: true,
				Answers: []snrdev.SuiteTestAnswersDB{
					{
						ID:          "answer-001",
						CreatedBy:   "system",
						ReferenceID: "suitetest-001",
						Question:    "What is the recommended diversification strategy?",
						Answer:      "Portfolio diversification across asset classes",
					},
					{
						ID:          "answer-002",
						CreatedBy:   "system",
						ReferenceID: "suitetest-001",
						Question:    "What is risk tolerance?",
						Answer:      "Ability to withstand investment losses",
					},
				},
			},

			Document: snrdev.DocumentsDB{
				ID:        "document-001",
				CreatedBy: "system",
				MemberID:  "member-001",
				DocTypes:  "ID_CARD",
				FileName:  "id_card_front.jpg",
				FilePath:  "/documents/member-001/id_card_front.jpg",
				FileTypes: "image/jpeg",
			},

			Addresses: []snrdev.AddressesDB{
				{
					ID:           "address-001",
					CreatedBy:    "system",
					MemberID:     "member-001",
					LocationCode: "10110",
					ProvinceCode: "10",
					Number:       "123",
					Floor:        "5",
					Village:      "Happy Village",
					Alley:        "Soi 15",
					Road:         "Sukhumvit Road",
					Subdistrict:  "Khlong Toei",
					District:     "Khlong Toei",
					Province:     "Bangkok",
					Zipcode:      "10110",
					CountryCode:  "TH",
					Type:         1,
				},
				{
					ID:           "address-002",
					CreatedBy:    "system",
					MemberID:     "member-001",
					LocationCode: "10200",
					ProvinceCode: "10",
					Number:       "456",
					Floor:        "10",
					Village:      "Work Plaza",
					Alley:        "Soi 20",
					Road:         "Silom Road",
					Subdistrict:  "Silom",
					District:     "Bang Rak",
					Province:     "Bangkok",
					Zipcode:      "10200",
					CountryCode:  "TH",
					Type:         3,
				},
			},

			SourceOfFund: snrdev.SourceOfFundsDB{
				ID:                         "sourcefund-001",
				CreatedBy:                  "system",
				MemberID:                   "member-001",
				SourceOfFunds:              "salary,investment",
				CountrySourceOfIncome:      "TH",
				PurposeOfInvestment:        "long_term_growth",
				CountrySourceIncomeVersion: "v1.0",
			},

			Occupation: snrdev.OccupationDB{
				ID:                  "occupation-001",
				CreateBy:            "system",
				MemberID:            "member-001",
				Education:           "bachelor_degree",
				EducationVersion:    "v1.0",
				SourceOfInvestment:  "salary,savings",
				Occupation:          "software_engineer",
				OccupationName:      "Software Engineer",
				VersionOfOccupation: "v1.0",
				Workplace:           "Tech Company Ltd.",
				JobPosition:         "Senior Developer",
				BusinessType:        "technology",
				BusinessTypeID:      "BT001",
				VersionOfBusiness:   "v1.0",
				MonthlyIncome:       "50,001-100,000",
				WithdrawalLimit:     "1,000,000",
			},

			Banks: []snrdev.BankDB{
				{
					ID:            "bank-001",
					CreatedBy:     "system",
					BankID:        1,
					MemberID:      "member-001",
					BankName:      "Kasikorn Bank",
					BranchName:    "Sukhumvit Branch",
					AccountNumber: "1234567890",
					BankVersion:   "v1.0",
					Type:          1,
				},
				{
					ID:            "bank-002",
					CreatedBy:     "system",
					BankID:        2,
					MemberID:      "member-001",
					BankName:      "Bangkok Bank",
					BranchName:    "Silom Branch",
					AccountNumber: "0987654321",
					BankVersion:   "v1.0",
					Type:          2,
				},
			},

			RiskScore: snrdev.RiskScoreDB{
				ID:                    "riskscore-001",
				MemberID:              "member-001",
				Occupation:            3,
				Politician:            0,
				Amlo:                  0,
				NotResidenceInThai:    0,
				CountryDetails:        "",
				ChangeToCash:          2,
				TransferAbleAsset:     1,
				GlobalProduct:         0,
				ProductHighRisk:       0,
				SouthernBorder:        0,
				SouthernBorderDetails: "",
				CountryRisk:           0,
				CountryRiskDetails:    "",
				ChannelRisk:           1,
				ChannelDetails:        "Online platform",
				SpecialHighRisk:       false,
				SpecialDetails:        "",
				Prohibited:            false,
				ProhibitDetails:       "",
			},

			Cdd: snrdev.CddDB{
				ID:           "cdd-001",
				MemberID:     "member-001",
				DopaMessage:  "DOPA verification successful",
				DopaStatus:   true,
				DopaDatetime: now,
				AmloMessage:  "AMLO check passed",
				AmloStatus:   true,
				AmloDatetime: now,
				LedMessage:   "LED check completed",
				LedStatus:    true,
				LedDatetime:  now,
				PepMessage:   "PEP check clear",
				PepStatus:    true,
				PepDatetime:  now,
				MuleMessage:  "Mule account check passed",
				MuleStatus:   true,
				MuleDatetime: now,
			},
		},
	}
	preCitizenshipExpectedHasAppmanResponse = snrdev.PreCitizenshipResp{
		RequestID: "",
		Status:    "",
		Member: snrdev.Member{
			ID:          "1",
			Mobile:      "0888888888",
			Email:       "john.doe@example.com",
			Citizenship: 1,
		},
		Step: 5,
		CustomerData: snrdev.CustomerData{
			ID:       "",
			Email:    "john.doe@example.com",
			Mobile:   "0888888888",
			Column:   "",
			MemberID: "1",
			Fullname: &snrdev.CustomerFullname{
				ID:           "1",
				MemberID:     "1",
				Citizenship:  1,
				Title:        "นาย",
				ThName:       "จอห์น",
				ThMiddleName: "",
				ThSurname:    "โด",
				EnName:       "John",
				EnMiddleName: "",
				EnSurname:    "Doe",
				Mobile:       "0888888888",
				Email:        "john.doe@example.com",
				Agreement:    true,
				Step:         5,
				Type:         1,
			},
			IDCard: &snrdev.IDCardDetail{
				DateOfBirth: now,
				Status:      1,
				IDCard:      "1234567890123",
				LaserCode:   "ABC123456789",
				ExpireDate:  now,
			},
			SuiteTest: &snrdev.SuiteTestDB{
				ID:          "suitetest-001",
				CreatedBy:   "system",
				MemberID:    "member-001",
				TotalScore:  85,
				Acknowledge: true,
				Answers: []snrdev.SuiteTestAnswersDB{
					{
						ID:          "answer-001",
						CreatedBy:   "system",
						DeletedBy:   "",
						ReferenceID: "suitetest-001",
						Question:    "What is the recommended diversification strategy?",
						Answer:      "Portfolio diversification across asset classes",
					},
					{
						ID:          "answer-002",
						CreatedBy:   "system",
						DeletedBy:   "",
						ReferenceID: "suitetest-001",
						Question:    "What is risk tolerance?",
						Answer:      "Ability to withstand investment losses",
					},
				},
			},
			Document: &snrdev.DocumentsDB{
				ID:        "document-001",
				CreatedBy: "system",
				MemberID:  "member-001",
				DocTypes:  "ID_CARD",
				FileName:  "id_card_front.jpg",
				FilePath:  "/documents/member-001/id_card_front.jpg",
				FileTypes: "image/jpeg",
			},
			Addresses: []snrdev.AddressesDB{
				{
					ID:           "address-001",
					CreatedBy:    "system",
					DeletedBy:    "",
					MemberID:     "member-001",
					LocationCode: "10110",
					ProvinceCode: "10",
					Number:       "123",
					Floor:        "5",
					Village:      "Happy Village",
					Alley:        "Soi 15",
					Road:         "Sukhumvit Road",
					Subdistrict:  "Khlong Toei",
					District:     "Khlong Toei",
					Province:     "Bangkok",
					Zipcode:      "10110",
					CountryCode:  "TH",
					Type:         1,
				},
				{
					ID:           "address-002",
					CreatedBy:    "system",
					DeletedBy:    "",
					MemberID:     "member-001",
					LocationCode: "10200",
					ProvinceCode: "10",
					Number:       "456",
					Floor:        "10",
					Village:      "Work Plaza",
					Alley:        "Soi 20",
					Road:         "Silom Road",
					Subdistrict:  "Silom",
					District:     "Bang Rak",
					Province:     "Bangkok",
					Zipcode:      "10200",
					CountryCode:  "TH",
					Type:         3,
				},
			},
			SourceOfFund: &snrdev.SourceOfFundsDB{
				ID:                         "sourcefund-001",
				CreatedBy:                  "system",
				MemberID:                   "member-001",
				SourceOfFunds:              "salary,investment",
				CountrySourceOfIncome:      "TH",
				PurposeOfInvestment:        "long_term_growth",
				CountrySourceIncomeVersion: "v1.0",
			},
			Occupation: &snrdev.OccupationDB{
				ID:                  "occupation-001",
				CreateBy:            "system",
				MemberID:            "member-001",
				Education:           "bachelor_degree",
				EducationVersion:    "v1.0",
				SourceOfInvestment:  "salary,savings",
				Occupation:          "software_engineer",
				OccupationName:      "Software Engineer",
				VersionOfOccupation: "v1.0",
				Workplace:           "Tech Company Ltd.",
				JobPosition:         "Senior Developer",
				BusinessType:        "technology",
				BusinessTypeID:      "BT001",
				VersionOfBusiness:   "v1.0",
				MonthlyIncome:       "50,001-100,000",
				WithdrawalLimit:     "1,000,000",
			},
			Banks: []snrdev.BankDB{
				{
					ID:            "bank-001",
					CreatedBy:     "system",
					DeletedBy:     "",
					BankID:        1,
					MemberID:      "member-001",
					BankName:      "Kasikorn Bank",
					BranchName:    "Sukhumvit Branch",
					AccountNumber: "1234567890",
					BankVersion:   "v1.0",
					Type:          1,
				},
				{
					ID:            "bank-002",
					CreatedBy:     "system",
					DeletedBy:     "",
					BankID:        2,
					MemberID:      "member-001",
					BankName:      "Bangkok Bank",
					BranchName:    "Silom Branch",
					AccountNumber: "0987654321",
					BankVersion:   "v1.0",
					Type:          2,
				},
			},
			KnowledgeTest: true,
		},
	}
	preCitizenshipExpectedNoAppmanResponse = snrdev.PreCitizenshipResp{
		RequestID: "",
		Status:    "",
		Member: snrdev.Member{
			ID:          "1",
			Mobile:      "0888888888",
			Email:       "john.doe@example.com",
			Citizenship: 0,
		},
		Step: 0,
		CustomerData: snrdev.CustomerData{
			ID:       "",
			Email:    "john.doe@example.com",
			Mobile:   "0888888888",
			Column:   "",
			MemberID: "1",
			Fullname: &snrdev.CustomerFullname{
				ID:           "1",
				MemberID:     "1",
				Citizenship:  1,
				Title:        "นาย",
				ThName:       "จอห์น",
				ThMiddleName: "",
				ThSurname:    "โด",
				EnName:       "John",
				EnMiddleName: "",
				EnSurname:    "Doe",
				Mobile:       "0888888888",
				Email:        "john.doe@example.com",
				Agreement:    true,
				Step:         5,
				Type:         1,
			},
			IDCard: &snrdev.IDCardDetail{
				DateOfBirth: now,
				Status:      1,
				IDCard:      "1234567890123",
				LaserCode:   "ABC123456789",
				ExpireDate:  now,
			},
			SuiteTest: &snrdev.SuiteTestDB{
				ID:          "suitetest-001",
				CreatedBy:   "system",
				MemberID:    "member-001",
				TotalScore:  85,
				Acknowledge: true,
				Answers: []snrdev.SuiteTestAnswersDB{
					{
						ID:          "answer-001",
						CreatedBy:   "system",
						DeletedBy:   "",
						ReferenceID: "suitetest-001",
						Question:    "What is the recommended diversification strategy?",
						Answer:      "Portfolio diversification across asset classes",
					},
					{
						ID:          "answer-002",
						CreatedBy:   "system",
						DeletedBy:   "",
						ReferenceID: "suitetest-001",
						Question:    "What is risk tolerance?",
						Answer:      "Ability to withstand investment losses",
					},
				},
			},
			Document: &snrdev.DocumentsDB{
				ID:        "document-001",
				CreatedBy: "system",
				MemberID:  "member-001",
				DocTypes:  "ID_CARD",
				FileName:  "id_card_front.jpg",
				FilePath:  "/documents/member-001/id_card_front.jpg",
				FileTypes: "image/jpeg",
			},
			Addresses: []snrdev.AddressesDB{
				{
					ID:           "address-001",
					CreatedBy:    "system",
					DeletedBy:    "",
					MemberID:     "member-001",
					LocationCode: "10110",
					ProvinceCode: "10",
					Number:       "123",
					Floor:        "5",
					Village:      "Happy Village",
					Alley:        "Soi 15",
					Road:         "Sukhumvit Road",
					Subdistrict:  "Khlong Toei",
					District:     "Khlong Toei",
					Province:     "Bangkok",
					Zipcode:      "10110",
					CountryCode:  "TH",
					Type:         1,
				},
				{
					ID:           "address-002",
					CreatedBy:    "system",
					DeletedBy:    "",
					MemberID:     "member-001",
					LocationCode: "10200",
					ProvinceCode: "10",
					Number:       "456",
					Floor:        "10",
					Village:      "Work Plaza",
					Alley:        "Soi 20",
					Road:         "Silom Road",
					Subdistrict:  "Silom",
					District:     "Bang Rak",
					Province:     "Bangkok",
					Zipcode:      "10200",
					CountryCode:  "TH",
					Type:         3,
				},
			},
			SourceOfFund: &snrdev.SourceOfFundsDB{
				ID:                         "sourcefund-001",
				CreatedBy:                  "system",
				MemberID:                   "member-001",
				SourceOfFunds:              "salary,investment",
				CountrySourceOfIncome:      "TH",
				PurposeOfInvestment:        "long_term_growth",
				CountrySourceIncomeVersion: "v1.0",
			},
			Occupation: &snrdev.OccupationDB{
				ID:                  "occupation-001",
				CreateBy:            "system",
				MemberID:            "member-001",
				Education:           "bachelor_degree",
				EducationVersion:    "v1.0",
				SourceOfInvestment:  "salary,savings",
				Occupation:          "software_engineer",
				OccupationName:      "Software Engineer",
				VersionOfOccupation: "v1.0",
				Workplace:           "Tech Company Ltd.",
				JobPosition:         "Senior Developer",
				BusinessType:        "technology",
				BusinessTypeID:      "BT001",
				VersionOfBusiness:   "v1.0",
				MonthlyIncome:       "50,001-100,000",
				WithdrawalLimit:     "1,000,000",
			},
			Banks: []snrdev.BankDB{
				{
					ID:            "bank-001",
					CreatedBy:     "system",
					DeletedBy:     "",
					BankID:        1,
					MemberID:      "member-001",
					BankName:      "Kasikorn Bank",
					BranchName:    "Sukhumvit Branch",
					AccountNumber: "1234567890",
					BankVersion:   "v1.0",
					Type:          1,
				},
				{
					ID:            "bank-002",
					CreatedBy:     "system",
					DeletedBy:     "",
					BankID:        2,
					MemberID:      "member-001",
					BankName:      "Bangkok Bank",
					BranchName:    "Silom Branch",
					AccountNumber: "0987654321",
					BankVersion:   "v1.0",
					Type:          2,
				},
			},
			KnowledgeTest: true,
		},
	}
)
