// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	snrdev "github.com/karn-zuvarna/snr-exam/app/snrdev"
	echo "github.com/labstack/echo/v4"
	gorm "gorm.io/gorm"
)

// MockIExternal is a mock of IExternal interface.
type MockIExternal struct {
	ctrl     *gomock.Controller
	recorder *MockIExternalMockRecorder
}

// MockIExternalMockRecorder is the mock recorder for MockIExternal.
type MockIExternalMockRecorder struct {
	mock *MockIExternal
}

// NewMockIExternal creates a new mock instance.
func NewMockIExternal(ctrl *gomock.Controller) *MockIExternal {
	mock := &MockIExternal{ctrl: ctrl}
	mock.recorder = &MockIExternalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIExternal) EXPECT() *MockIExternalMockRecorder {
	return m.recorder
}

// GenUuid mocks base method.
func (m *MockIExternal) GenUuid() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenUuid")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenUuid indicates an expected call of GenUuid.
func (mr *MockIExternalMockRecorder) GenUuid() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenUuid", reflect.TypeOf((*MockIExternal)(nil).GenUuid))
}

// GetIP mocks base method.
func (m *MockIExternal) GetIP(c echo.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIP", c)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIP indicates an expected call of GetIP.
func (mr *MockIExternalMockRecorder) GetIP(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIP", reflect.TypeOf((*MockIExternal)(nil).GetIP), c)
}

// GetTimeNow mocks base method.
func (m *MockIExternal) GetTimeNow() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeNow")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetTimeNow indicates an expected call of GetTimeNow.
func (mr *MockIExternalMockRecorder) GetTimeNow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeNow", reflect.TypeOf((*MockIExternal)(nil).GetTimeNow))
}

// MockIServiceRiskScore is a mock of IServiceRiskScore interface.
type MockIServiceRiskScore struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceRiskScoreMockRecorder
}

// MockIServiceRiskScoreMockRecorder is the mock recorder for MockIServiceRiskScore.
type MockIServiceRiskScoreMockRecorder struct {
	mock *MockIServiceRiskScore
}

// NewMockIServiceRiskScore creates a new mock instance.
func NewMockIServiceRiskScore(ctrl *gomock.Controller) *MockIServiceRiskScore {
	mock := &MockIServiceRiskScore{ctrl: ctrl}
	mock.recorder = &MockIServiceRiskScoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIServiceRiskScore) EXPECT() *MockIServiceRiskScoreMockRecorder {
	return m.recorder
}

// LocationAndCustomerRisk mocks base method.
func (m *MockIServiceRiskScore) LocationAndCustomerRisk(ctx context.Context, tx *gorm.DB, funds *snrdev.SourceOfFundsDB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocationAndCustomerRisk", ctx, tx, funds)
	ret0, _ := ret[0].(error)
	return ret0
}

// LocationAndCustomerRisk indicates an expected call of LocationAndCustomerRisk.
func (mr *MockIServiceRiskScoreMockRecorder) LocationAndCustomerRisk(ctx, tx, funds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocationAndCustomerRisk", reflect.TypeOf((*MockIServiceRiskScore)(nil).LocationAndCustomerRisk), ctx, tx, funds)
}

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// VerifyToken mocks base method.
func (m *MockIService) VerifyToken(tokenStr string, keyData []byte) (snrdev.PreCitizenToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", tokenStr, keyData)
	ret0, _ := ret[0].(snrdev.PreCitizenToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockIServiceMockRecorder) VerifyToken(tokenStr, keyData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockIService)(nil).VerifyToken), tokenStr, keyData)
}

// MockIPreMember is a mock of IPreMember interface.
type MockIPreMember struct {
	ctrl     *gomock.Controller
	recorder *MockIPreMemberMockRecorder
}

// MockIPreMemberMockRecorder is the mock recorder for MockIPreMember.
type MockIPreMemberMockRecorder struct {
	mock *MockIPreMember
}

// NewMockIPreMember creates a new mock instance.
func NewMockIPreMember(ctrl *gomock.Controller) *MockIPreMember {
	mock := &MockIPreMember{ctrl: ctrl}
	mock.recorder = &MockIPreMemberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPreMember) EXPECT() *MockIPreMemberMockRecorder {
	return m.recorder
}

// CreateAll mocks base method.
func (m *MockIPreMember) CreateAll(ctx context.Context, tx *gorm.DB, preMember *[]snrdev.PreMemberDB, scope ...func(*gorm.DB) *gorm.DB) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, tx, preMember}
	for _, a := range scope {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateAll", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAll indicates an expected call of CreateAll.
func (mr *MockIPreMemberMockRecorder) CreateAll(ctx, tx, preMember interface{}, scope ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, tx, preMember}, scope...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAll", reflect.TypeOf((*MockIPreMember)(nil).CreateAll), varargs...)
}

// GetAll mocks base method.
func (m *MockIPreMember) GetAll(ctx context.Context, tx *gorm.DB, preMember *[]snrdev.PreMemberDB, scope ...func(*gorm.DB) *gorm.DB) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, tx, preMember}
	for _, a := range scope {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIPreMemberMockRecorder) GetAll(ctx, tx, preMember interface{}, scope ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, tx, preMember}, scope...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIPreMember)(nil).GetAll), varargs...)
}

// JoinCustomer mocks base method.
func (m *MockIPreMember) JoinCustomer(ctx context.Context, tx *gorm.DB, preMember *[]snrdev.PreMemberDB, scope ...func(*gorm.DB) *gorm.DB) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, tx, preMember}
	for _, a := range scope {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "JoinCustomer", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinCustomer indicates an expected call of JoinCustomer.
func (mr *MockIPreMemberMockRecorder) JoinCustomer(ctx, tx, preMember interface{}, scope ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, tx, preMember}, scope...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinCustomer", reflect.TypeOf((*MockIPreMember)(nil).JoinCustomer), varargs...)
}

// UpdateAll mocks base method.
func (m *MockIPreMember) UpdateAll(ctx context.Context, tx *gorm.DB, preMember *snrdev.PreMemberDB, scope ...func(*gorm.DB) *gorm.DB) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, tx, preMember}
	for _, a := range scope {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateAll", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAll indicates an expected call of UpdateAll.
func (mr *MockIPreMemberMockRecorder) UpdateAll(ctx, tx, preMember interface{}, scope ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, tx, preMember}, scope...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAll", reflect.TypeOf((*MockIPreMember)(nil).UpdateAll), varargs...)
}

// MockIIDcard is a mock of IIDcard interface.
type MockIIDcard struct {
	ctrl     *gomock.Controller
	recorder *MockIIDcardMockRecorder
}

// MockIIDcardMockRecorder is the mock recorder for MockIIDcard.
type MockIIDcardMockRecorder struct {
	mock *MockIIDcard
}

// NewMockIIDcard creates a new mock instance.
func NewMockIIDcard(ctrl *gomock.Controller) *MockIIDcard {
	mock := &MockIIDcard{ctrl: ctrl}
	mock.recorder = &MockIIDcardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIIDcard) EXPECT() *MockIIDcardMockRecorder {
	return m.recorder
}

// MockICustomer is a mock of ICustomer interface.
type MockICustomer struct {
	ctrl     *gomock.Controller
	recorder *MockICustomerMockRecorder
}

// MockICustomerMockRecorder is the mock recorder for MockICustomer.
type MockICustomerMockRecorder struct {
	mock *MockICustomer
}

// NewMockICustomer creates a new mock instance.
func NewMockICustomer(ctrl *gomock.Controller) *MockICustomer {
	mock := &MockICustomer{ctrl: ctrl}
	mock.recorder = &MockICustomerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICustomer) EXPECT() *MockICustomerMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockICustomer) GetAll(ctx context.Context, tx *gorm.DB, customer *[]snrdev.CustomerDetailsDB, scope ...func(*gorm.DB) *gorm.DB) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, tx, customer}
	for _, a := range scope {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockICustomerMockRecorder) GetAll(ctx, tx, customer interface{}, scope ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, tx, customer}, scope...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockICustomer)(nil).GetAll), varargs...)
}

// MockISuitetest is a mock of ISuitetest interface.
type MockISuitetest struct {
	ctrl     *gomock.Controller
	recorder *MockISuitetestMockRecorder
}

// MockISuitetestMockRecorder is the mock recorder for MockISuitetest.
type MockISuitetestMockRecorder struct {
	mock *MockISuitetest
}

// NewMockISuitetest creates a new mock instance.
func NewMockISuitetest(ctrl *gomock.Controller) *MockISuitetest {
	mock := &MockISuitetest{ctrl: ctrl}
	mock.recorder = &MockISuitetestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISuitetest) EXPECT() *MockISuitetestMockRecorder {
	return m.recorder
}

// MockIAnswer is a mock of IAnswer interface.
type MockIAnswer struct {
	ctrl     *gomock.Controller
	recorder *MockIAnswerMockRecorder
}

// MockIAnswerMockRecorder is the mock recorder for MockIAnswer.
type MockIAnswerMockRecorder struct {
	mock *MockIAnswer
}

// NewMockIAnswer creates a new mock instance.
func NewMockIAnswer(ctrl *gomock.Controller) *MockIAnswer {
	mock := &MockIAnswer{ctrl: ctrl}
	mock.recorder = &MockIAnswerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAnswer) EXPECT() *MockIAnswerMockRecorder {
	return m.recorder
}

// MockIAppman is a mock of IAppman interface.
type MockIAppman struct {
	ctrl     *gomock.Controller
	recorder *MockIAppmanMockRecorder
}

// MockIAppmanMockRecorder is the mock recorder for MockIAppman.
type MockIAppmanMockRecorder struct {
	mock *MockIAppman
}

// NewMockIAppman creates a new mock instance.
func NewMockIAppman(ctrl *gomock.Controller) *MockIAppman {
	mock := &MockIAppman{ctrl: ctrl}
	mock.recorder = &MockIAppmanMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAppman) EXPECT() *MockIAppmanMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockIAppman) GetAll(ctx context.Context, tx *gorm.DB, appman *[]snrdev.AppmanDB, scope ...func(*gorm.DB) *gorm.DB) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, tx, appman}
	for _, a := range scope {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIAppmanMockRecorder) GetAll(ctx, tx, appman interface{}, scope ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, tx, appman}, scope...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIAppman)(nil).GetAll), varargs...)
}

// MockIDocument is a mock of IDocument interface.
type MockIDocument struct {
	ctrl     *gomock.Controller
	recorder *MockIDocumentMockRecorder
}

// MockIDocumentMockRecorder is the mock recorder for MockIDocument.
type MockIDocumentMockRecorder struct {
	mock *MockIDocument
}

// NewMockIDocument creates a new mock instance.
func NewMockIDocument(ctrl *gomock.Controller) *MockIDocument {
	mock := &MockIDocument{ctrl: ctrl}
	mock.recorder = &MockIDocumentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDocument) EXPECT() *MockIDocumentMockRecorder {
	return m.recorder
}

// MockIAddress is a mock of IAddress interface.
type MockIAddress struct {
	ctrl     *gomock.Controller
	recorder *MockIAddressMockRecorder
}

// MockIAddressMockRecorder is the mock recorder for MockIAddress.
type MockIAddressMockRecorder struct {
	mock *MockIAddress
}

// NewMockIAddress creates a new mock instance.
func NewMockIAddress(ctrl *gomock.Controller) *MockIAddress {
	mock := &MockIAddress{ctrl: ctrl}
	mock.recorder = &MockIAddressMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAddress) EXPECT() *MockIAddressMockRecorder {
	return m.recorder
}

// MockISourceOfFunds is a mock of ISourceOfFunds interface.
type MockISourceOfFunds struct {
	ctrl     *gomock.Controller
	recorder *MockISourceOfFundsMockRecorder
}

// MockISourceOfFundsMockRecorder is the mock recorder for MockISourceOfFunds.
type MockISourceOfFundsMockRecorder struct {
	mock *MockISourceOfFunds
}

// NewMockISourceOfFunds creates a new mock instance.
func NewMockISourceOfFunds(ctrl *gomock.Controller) *MockISourceOfFunds {
	mock := &MockISourceOfFunds{ctrl: ctrl}
	mock.recorder = &MockISourceOfFundsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISourceOfFunds) EXPECT() *MockISourceOfFundsMockRecorder {
	return m.recorder
}

// MockIBank is a mock of IBank interface.
type MockIBank struct {
	ctrl     *gomock.Controller
	recorder *MockIBankMockRecorder
}

// MockIBankMockRecorder is the mock recorder for MockIBank.
type MockIBankMockRecorder struct {
	mock *MockIBank
}

// NewMockIBank creates a new mock instance.
func NewMockIBank(ctrl *gomock.Controller) *MockIBank {
	mock := &MockIBank{ctrl: ctrl}
	mock.recorder = &MockIBankMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBank) EXPECT() *MockIBankMockRecorder {
	return m.recorder
}

// MockIOccupation is a mock of IOccupation interface.
type MockIOccupation struct {
	ctrl     *gomock.Controller
	recorder *MockIOccupationMockRecorder
}

// MockIOccupationMockRecorder is the mock recorder for MockIOccupation.
type MockIOccupationMockRecorder struct {
	mock *MockIOccupation
}

// NewMockIOccupation creates a new mock instance.
func NewMockIOccupation(ctrl *gomock.Controller) *MockIOccupation {
	mock := &MockIOccupation{ctrl: ctrl}
	mock.recorder = &MockIOccupationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOccupation) EXPECT() *MockIOccupationMockRecorder {
	return m.recorder
}

// MockILiveness is a mock of ILiveness interface.
type MockILiveness struct {
	ctrl     *gomock.Controller
	recorder *MockILivenessMockRecorder
}

// MockILivenessMockRecorder is the mock recorder for MockILiveness.
type MockILivenessMockRecorder struct {
	mock *MockILiveness
}

// NewMockILiveness creates a new mock instance.
func NewMockILiveness(ctrl *gomock.Controller) *MockILiveness {
	mock := &MockILiveness{ctrl: ctrl}
	mock.recorder = &MockILivenessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILiveness) EXPECT() *MockILivenessMockRecorder {
	return m.recorder
}

// MockILivenessAttributes is a mock of ILivenessAttributes interface.
type MockILivenessAttributes struct {
	ctrl     *gomock.Controller
	recorder *MockILivenessAttributesMockRecorder
}

// MockILivenessAttributesMockRecorder is the mock recorder for MockILivenessAttributes.
type MockILivenessAttributesMockRecorder struct {
	mock *MockILivenessAttributes
}

// NewMockILivenessAttributes creates a new mock instance.
func NewMockILivenessAttributes(ctrl *gomock.Controller) *MockILivenessAttributes {
	mock := &MockILivenessAttributes{ctrl: ctrl}
	mock.recorder = &MockILivenessAttributesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILivenessAttributes) EXPECT() *MockILivenessAttributesMockRecorder {
	return m.recorder
}

// MockIRecognition is a mock of IRecognition interface.
type MockIRecognition struct {
	ctrl     *gomock.Controller
	recorder *MockIRecognitionMockRecorder
}

// MockIRecognitionMockRecorder is the mock recorder for MockIRecognition.
type MockIRecognitionMockRecorder struct {
	mock *MockIRecognition
}

// NewMockIRecognition creates a new mock instance.
func NewMockIRecognition(ctrl *gomock.Controller) *MockIRecognition {
	mock := &MockIRecognition{ctrl: ctrl}
	mock.recorder = &MockIRecognitionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRecognition) EXPECT() *MockIRecognitionMockRecorder {
	return m.recorder
}

// MockIWatchList is a mock of IWatchList interface.
type MockIWatchList struct {
	ctrl     *gomock.Controller
	recorder *MockIWatchListMockRecorder
}

// MockIWatchListMockRecorder is the mock recorder for MockIWatchList.
type MockIWatchListMockRecorder struct {
	mock *MockIWatchList
}

// NewMockIWatchList creates a new mock instance.
func NewMockIWatchList(ctrl *gomock.Controller) *MockIWatchList {
	mock := &MockIWatchList{ctrl: ctrl}
	mock.recorder = &MockIWatchListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWatchList) EXPECT() *MockIWatchListMockRecorder {
	return m.recorder
}

// MockCddStatus is a mock of CddStatus interface.
type MockCddStatus struct {
	ctrl     *gomock.Controller
	recorder *MockCddStatusMockRecorder
}

// MockCddStatusMockRecorder is the mock recorder for MockCddStatus.
type MockCddStatusMockRecorder struct {
	mock *MockCddStatus
}

// NewMockCddStatus creates a new mock instance.
func NewMockCddStatus(ctrl *gomock.Controller) *MockCddStatus {
	mock := &MockCddStatus{ctrl: ctrl}
	mock.recorder = &MockCddStatusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCddStatus) EXPECT() *MockCddStatusMockRecorder {
	return m.recorder
}

// MockIRiskOccupation is a mock of IRiskOccupation interface.
type MockIRiskOccupation struct {
	ctrl     *gomock.Controller
	recorder *MockIRiskOccupationMockRecorder
}

// MockIRiskOccupationMockRecorder is the mock recorder for MockIRiskOccupation.
type MockIRiskOccupationMockRecorder struct {
	mock *MockIRiskOccupation
}

// NewMockIRiskOccupation creates a new mock instance.
func NewMockIRiskOccupation(ctrl *gomock.Controller) *MockIRiskOccupation {
	mock := &MockIRiskOccupation{ctrl: ctrl}
	mock.recorder = &MockIRiskOccupationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRiskOccupation) EXPECT() *MockIRiskOccupationMockRecorder {
	return m.recorder
}

// MockIRiskCountry is a mock of IRiskCountry interface.
type MockIRiskCountry struct {
	ctrl     *gomock.Controller
	recorder *MockIRiskCountryMockRecorder
}

// MockIRiskCountryMockRecorder is the mock recorder for MockIRiskCountry.
type MockIRiskCountryMockRecorder struct {
	mock *MockIRiskCountry
}

// NewMockIRiskCountry creates a new mock instance.
func NewMockIRiskCountry(ctrl *gomock.Controller) *MockIRiskCountry {
	mock := &MockIRiskCountry{ctrl: ctrl}
	mock.recorder = &MockIRiskCountryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRiskCountry) EXPECT() *MockIRiskCountryMockRecorder {
	return m.recorder
}

// MockIRiskScore is a mock of IRiskScore interface.
type MockIRiskScore struct {
	ctrl     *gomock.Controller
	recorder *MockIRiskScoreMockRecorder
}

// MockIRiskScoreMockRecorder is the mock recorder for MockIRiskScore.
type MockIRiskScoreMockRecorder struct {
	mock *MockIRiskScore
}

// NewMockIRiskScore creates a new mock instance.
func NewMockIRiskScore(ctrl *gomock.Controller) *MockIRiskScore {
	mock := &MockIRiskScore{ctrl: ctrl}
	mock.recorder = &MockIRiskScoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRiskScore) EXPECT() *MockIRiskScoreMockRecorder {
	return m.recorder
}

// MockIJoin is a mock of IJoin interface.
type MockIJoin struct {
	ctrl     *gomock.Controller
	recorder *MockIJoinMockRecorder
}

// MockIJoinMockRecorder is the mock recorder for MockIJoin.
type MockIJoinMockRecorder struct {
	mock *MockIJoin
}

// NewMockIJoin creates a new mock instance.
func NewMockIJoin(ctrl *gomock.Controller) *MockIJoin {
	mock := &MockIJoin{ctrl: ctrl}
	mock.recorder = &MockIJoinMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIJoin) EXPECT() *MockIJoinMockRecorder {
	return m.recorder
}

// MockICdd is a mock of ICdd interface.
type MockICdd struct {
	ctrl     *gomock.Controller
	recorder *MockICddMockRecorder
}

// MockICddMockRecorder is the mock recorder for MockICdd.
type MockICddMockRecorder struct {
	mock *MockICdd
}

// NewMockICdd creates a new mock instance.
func NewMockICdd(ctrl *gomock.Controller) *MockICdd {
	mock := &MockICdd{ctrl: ctrl}
	mock.recorder = &MockICddMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICdd) EXPECT() *MockICddMockRecorder {
	return m.recorder
}

// MockIMasterLocation is a mock of IMasterLocation interface.
type MockIMasterLocation struct {
	ctrl     *gomock.Controller
	recorder *MockIMasterLocationMockRecorder
}

// MockIMasterLocationMockRecorder is the mock recorder for MockIMasterLocation.
type MockIMasterLocationMockRecorder struct {
	mock *MockIMasterLocation
}

// NewMockIMasterLocation creates a new mock instance.
func NewMockIMasterLocation(ctrl *gomock.Controller) *MockIMasterLocation {
	mock := &MockIMasterLocation{ctrl: ctrl}
	mock.recorder = &MockIMasterLocationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMasterLocation) EXPECT() *MockIMasterLocationMockRecorder {
	return m.recorder
}

// MockIMasterCountry is a mock of IMasterCountry interface.
type MockIMasterCountry struct {
	ctrl     *gomock.Controller
	recorder *MockIMasterCountryMockRecorder
}

// MockIMasterCountryMockRecorder is the mock recorder for MockIMasterCountry.
type MockIMasterCountryMockRecorder struct {
	mock *MockIMasterCountry
}

// NewMockIMasterCountry creates a new mock instance.
func NewMockIMasterCountry(ctrl *gomock.Controller) *MockIMasterCountry {
	mock := &MockIMasterCountry{ctrl: ctrl}
	mock.recorder = &MockIMasterCountryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMasterCountry) EXPECT() *MockIMasterCountryMockRecorder {
	return m.recorder
}

// MockIMasterOccupation is a mock of IMasterOccupation interface.
type MockIMasterOccupation struct {
	ctrl     *gomock.Controller
	recorder *MockIMasterOccupationMockRecorder
}

// MockIMasterOccupationMockRecorder is the mock recorder for MockIMasterOccupation.
type MockIMasterOccupationMockRecorder struct {
	mock *MockIMasterOccupation
}

// NewMockIMasterOccupation creates a new mock instance.
func NewMockIMasterOccupation(ctrl *gomock.Controller) *MockIMasterOccupation {
	mock := &MockIMasterOccupation{ctrl: ctrl}
	mock.recorder = &MockIMasterOccupationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMasterOccupation) EXPECT() *MockIMasterOccupationMockRecorder {
	return m.recorder
}
